const PROJECTS={
  'indra-suci':{title:'Indra & Suci',category:'Prewedding',year:'2024',cover:'/assets/video/indra-suci.jpg',video:'7RwTWRgLmHY',description:'Prewedding session with an emphasis on natural movement, location, and the relationship between the couple.',gallery:['/assets/brand/instagram/ig-01.jpg','/assets/brand/instagram/ig-05.jpg'],source:'https://www.youtube.com/watch?v=7RwTWRgLmHY'},
  'eka-nanda':{title:'Eka & Nanda',category:'Prewedding',year:'2024',cover:'/assets/video/eka-nanda.jpg',video:'8kSnL2fBCTU',description:'A location-led prewedding film with a relaxed pace and a clear focus on the couple.',gallery:['/assets/brand/instagram/ig-05.jpg','/assets/brand/instagram/ig-01.jpg'],source:'https://www.youtube.com/watch?v=8kSnL2fBCTU'},
  'bukit-lestari':{title:'Puncak Bukit Lestari',category:'Commercial / Destination',year:'2023',cover:'/assets/video/bukit-lestari.jpg',video:'t4hcCZhzOdo',description:'Promotional film for a destination property, built around landscape, atmosphere, and place.',gallery:['/assets/brand/instagram/ig-02.jpg','/assets/portfolio/wedding-cinematic-bali.jpg'],source:'https://www.youtube.com/watch?v=t4hcCZhzOdo'},
  'blooms-short':{title:'The Blooms Garden Bali',category:'Destination / Commercial',year:'2023',cover:'/assets/video/blooms-short.jpg',video:'bIOMXfEdCEc',description:'Short-form promotional edit for a destination in Bali.',gallery:['/assets/brand/instagram/ig-02.jpg','/assets/portfolio/event-reels-highlight-01.jpg'],source:'https://www.youtube.com/watch?v=bIOMXfEdCEc'},
  'blooms-promo':{title:'The Blooms Garden — Promotional Video',category:'Destination / Commercial',year:'2023',cover:'/assets/video/blooms-promo.jpg',video:'h6Q0_5upkk4',description:'A promotional video focused on the experience, setting, and visual identity of the destination.',gallery:['/assets/brand/instagram/ig-02.jpg','/assets/portfolio/wedding-highlight-teaser.jpg'],source:'https://www.youtube.com/watch?v=h6Q0_5upkk4'},
  'mandiri-taspen':{title:'PT Bank Mandiri Taspen',category:'Corporate',year:'2023',cover:'/assets/video/mandiri-taspen.jpg',video:'Gi4BH7nQQXo',description:'Corporate learning centre documentation and promotional video production.',gallery:['/assets/brand/instagram/ig-03.jpg','/assets/portfolio/corporate-mini-profile.jpg'],source:'https://www.youtube.com/watch?v=Gi4BH7nQQXo'},
  'wedding-ceremony':{title:'Wedding Ceremony',category:'Wedding',year:'Portfolio',cover:'/assets/brand/instagram/ig-05.jpg',video:'',description:'Ceremony coverage with a documentary approach to people, details, and atmosphere.',gallery:['/assets/brand/instagram/ig-01.jpg','/assets/brand/instagram/ig-04.jpg','/assets/brand/instagram/ig-06.jpg'],source:'https://www.instagram.com/mellogangvisuals/'},
  'cultural-event':{title:'Cultural Event',category:'Event',year:'Portfolio',cover:'/assets/brand/instagram/ig-02.jpg',video:'',description:'Environmental and documentary coverage for cultural events and public celebrations.',gallery:['/assets/brand/instagram/ig-03.jpg','/assets/brand/instagram/ig-04.jpg','/assets/brand/instagram/ig-06.jpg'],source:'https://www.instagram.com/mellogangvisuals/'}
};
const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];
function theme(){const root=document.documentElement;const stored=localStorage.getItem('mellogang-theme');if(stored)root.dataset.theme=stored;const buttons=[$('#themeToggle'),$('#mobileThemeToggle')].filter(Boolean);if(!buttons.length)return;const update=()=>{const dark=root.dataset.theme==='dark';buttons.forEach(button=>{button.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');if(button.id==='themeToggle')button.innerHTML=dark?'☼':'☾';else button.textContent=dark?'Use light theme':'Use dark theme'})};update();buttons.forEach(button=>button.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('mellogang-theme',root.dataset.theme);update()}))}
function menu(){const b=$('#menuButton'),m=$('#mobileMenu');if(!b||!m)return;b.addEventListener('click',()=>{const open=m.hasAttribute('hidden');if(open)m.removeAttribute('hidden');else m.setAttribute('hidden','');b.setAttribute('aria-expanded',String(open))})}
function reveal(){const els=$$('.reveal');if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('ready'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('ready');io.unobserve(e.target)}}),{threshold:.1});els.forEach(e=>io.observe(e))}
function gsapMotion(){if(window.matchMedia('(prefers-reduced-motion: reduce)').matches||!window.gsap)return;const gsap=window.gsap;gsap.registerPlugin(window.ScrollTrigger);gsap.utils.toArray('.hero-image img').forEach(img=>gsap.to(img,{yPercent:7,scale:1.08,ease:'none',scrollTrigger:{trigger:img,start:'top bottom',end:'bottom top',scrub:1}}));gsap.utils.toArray('.section-dark,.works-grid,.about-strip,.book-layout').forEach(el=>gsap.from(el,{y:28,opacity:0,duration:.8,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 82%',once:true}}));}
function detail(){const node=$('[data-project]');if(!node)return;const project=PROJECTS[node.dataset.project];if(!project)return;const title=$('[data-detail-title]');if(title)title.textContent=project.title;const category=$('[data-detail-category]');if(category)category.textContent=project.category;const year=$('[data-detail-year]');if(year)year.textContent=project.year;const description=$('[data-detail-description]');if(description)description.textContent=project.description;const cover=$('[data-detail-cover]');if(cover){cover.src=project.cover;cover.alt=project.title}const frame=$('[data-detail-video]');if(frame&&project.video)frame.innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${project.video}?rel=0&modestbranding=1" title="${project.title}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`;else if(frame)frame.innerHTML='<div class="video-empty">Video preview is available through the project source.</div>';const gallery=$('[data-detail-gallery]');if(gallery)gallery.innerHTML=project.gallery.map((src,i)=>`<img src="${src}" alt="${project.title} — frame ${i+1}" loading="lazy">`).join('');const source=$('[data-detail-source]');if(source){source.href=project.source;source.textContent=project.source.includes('youtube')?'Watch on YouTube ↗':'View on Instagram ↗'}document.title=`${project.title} — MellogangVisuals`}
function booking(){const form=$('#bookForm');if(!form)return;const select=$('#bookPackage'),name=$('#bookName'),date=$('#bookDate'),notes=$('#bookNotes');const update=()=>{const label=select.options[select.selectedIndex]?.text||'photo/video production';const d=date.value?new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${date.value}T00:00:00`)):'[tanggal acara]';const text=`Hi MellogangVisuals, saya ${name.value.trim()||'[nama]'}. Saya ingin menanyakan ketersediaan untuk ${label} pada tanggal ${d}.${notes.value.trim()?` Catatan: ${notes.value.trim()}`:''} Mohon info detail dan langkah selanjutnya ya.`;const link=`https://wa.me/6282236004917?text=${encodeURIComponent(text)}`;const output=$('#waLink');if(output)output.href=link};[select,name,date,notes].forEach(e=>e?.addEventListener('input',update));form.addEventListener('submit',e=>{e.preventDefault();update();window.open($('#waLink').href,'_blank','noopener,noreferrer')});update()}
document.addEventListener('DOMContentLoaded',()=>{theme();menu();reveal();gsapMotion();detail();booking()});
